/*
  # Add tags field to software submissions

  1. Changes
    - Add `tags` column to `software_submissions` table
      - Type: text[] (array of text)
      - Default: empty array
      - Stores AI-generated or user-provided tags for categorization
  
  2. Notes
    - Tags will be generated by AI based on software description and metadata
    - Multiple tags can be assigned to each submission
    - Tags help with search and filtering functionality
*/

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'software_submissions' AND column_name = 'tags'
  ) THEN
    ALTER TABLE software_submissions ADD COLUMN tags text[] DEFAULT '{}';
  END IF;
END $$;